# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgsLandspy
                                 A QGIS plugin
 Landscape analysis with QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-23
        copyright            : (C) 2022 by J. Vicente Pérez
        email                : vperez@go.ugr.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QgsTopopy class from file QgsTopopy.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgs_landspy import QgsLandspy
    return QgsLandspy(iface)
